/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudentInformation.java
 *
 * Created on 11 May, 2016, 4:50:14 PM
 */

package com.student.project;

import javax.swing.JFrame;

/**
 *
 * @author YASH KUMAR
 */
public class StudentInformation extends javax.swing.JPanel {

    /** Creates new form StudentInformation */
    public StudentInformation() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtf2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtf3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtf4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtf5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtf6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtf7 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jcb1 = new javax.swing.JComboBox();
        jcb2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("STUDENT INFORMATION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, 28));

        jLabel2.setText("ENROLLMENT NO.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));
        add(jtf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 160, -1));

        jLabel3.setText("BRANCH");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, 20));

        jLabel4.setText("STUDENT FIRST NAME");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));
        add(jtf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 160, -1));

        jLabel5.setText("LAST NAME");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, 20));
        add(jtf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 170, -1));

        jLabel6.setText("FATHER`S NAME");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 20));
        add(jtf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 160, -1));

        jLabel7.setText("SEM");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jLabel8.setText("MOBILE NO.");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        add(jtf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 160, -1));

        jLabel9.setText("EMAIL ID");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, 20));
        add(jtf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 170, -1));

        jtf7.setColumns(20);
        jtf7.setRows(5);
        jScrollPane1.setViewportView(jtf7);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 310, 60));

        jLabel10.setText("ADDRESS");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jcb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IT", "CSE", "EC", "ME", "CE", "EX" }));
        add(jcb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 100, -1));

        jcb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        add(jcb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 100, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("UPDATE");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        s.setsenrollno(jtf1.getText());
        s.setSfirstname(jtf2.getText());
        s.setSlastname(jtf3.getText());
        s.setSfname(jtf4.getText());
        s.setSbranch(jcb1.getSelectedItem().toString());
        //System.out.print(jcb1.getSelectedItem().toString());
        //System.out.print(Integer.parseInt(jcb2.getSelectedItem().toString()));

        s.setSsem(Integer.parseInt(jcb2.getSelectedItem().toString()));
      //  System.out.print(jcb2.getName());
        s.setSmobile(jtf5.getText());
        s.setSemail(jtf6.getText());
        s.setSaddress(jtf7.getText());
        boolean b=s.add();
        if(b){
            jLabel11.setText("Data Recorded Successfully");





        }
 else{
            jLabel11.setText("Please Datafill Correctively");
 }


    }//GEN-LAST:event_jButton1ActionPerformed
    public static void main(String ar[]){
        JFrame f=new JFrame("student information");
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setContentPane(new StudentInformation());
        f.setBounds(10, 10, 700, 700);
        f.setVisible(true);
    }
StudentBean s=new StudentBean();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcb1;
    private javax.swing.JComboBox jcb2;
    private javax.swing.JTextField jtf1;
    private javax.swing.JTextField jtf2;
    private javax.swing.JTextField jtf3;
    private javax.swing.JTextField jtf4;
    private javax.swing.JTextField jtf5;
    private javax.swing.JTextField jtf6;
    private javax.swing.JTextArea jtf7;
    // End of variables declaration//GEN-END:variables

}
