package com.student.attendance;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Attendanceupdationform.java
 *
 * Created on 6 May, 2016, 2:53:21 PM
 */



/**
 *
 * @author YASH KUMAR
 */
public class AttendanceUpdationform extends javax.swing.JFrame {
static double ttotal=0,tattended=0,tpercentage=0,ptotal=0,pattended=0,ppercentage=0,aspecial=0,afinal=0;
    /** Creates new form Attendanceupdationform */
    public AttendanceUpdationform() {
        initComponents();

        StudentBean s=new StudentBean();
        jButton3.setEnabled(false);
        jtf13.setEditable(false);
        jtf17.setEditable(false);
       jtf18.setEditable(false);
        // jcb2.setToolTipText(s.setSbranch());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtf2 = new javax.swing.JTextField();
        jtf3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtf4 = new javax.swing.JTextField();
        jcb2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jtf5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtf6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtf7 = new javax.swing.JTextArea();
        jcb1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtf12 = new javax.swing.JTextField();
        jtf13 = new javax.swing.JTextField();
        jtf14 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtf15 = new javax.swing.JTextField();
        jtf16 = new javax.swing.JTextField();
        jtf17 = new javax.swing.JTextField();
        jtf18 = new javax.swing.JTextField();
        jtf11 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabel1.setText("Attendance Update Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 11, 323, 54));

        jLabel2.setText("ENROLLMENT NO.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 128, 112, 21));
        getContentPane().add(jtf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 112, 169, 30));

        jLabel3.setText("BRANCH:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 116, 75, 22));

        jLabel4.setText("FIRST NAME:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 167, 76, -1));

        jLabel5.setText("LAST NAME:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 163, 84, 22));
        getContentPane().add(jtf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 160, 169, 29));

        jtf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf3ActionPerformed(evt);
            }
        });
        getContentPane().add(jtf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 160, 149, 28));

        jLabel6.setText("FATHER'S NAME:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 215, -1, -1));

        jLabel7.setText("SEMESTER:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 211, 84, 23));
        getContentPane().add(jtf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 207, 169, 31));

        jcb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jcb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb2ActionPerformed(evt);
            }
        });
        getContentPane().add(jcb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 209, 66, 26));

        jLabel8.setText("MOBILE NO.:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 256, 82, -1));

        jtf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf5ActionPerformed(evt);
            }
        });
        getContentPane().add(jtf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 256, 169, 30));

        jLabel9.setText("EMAIL ID.:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 256, 84, 30));

        jtf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf6ActionPerformed(evt);
            }
        });
        getContentPane().add(jtf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 256, 149, 30));

        jLabel10.setText("ADDRESS:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 304, -1, -1));

        jtf7.setColumns(20);
        jtf7.setRows(5);
        jScrollPane1.setViewportView(jtf7);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 304, 241, 49));

        jcb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IT", "AU", "EX", "EC", "CSE", "CE", "ME", " " }));
        jcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb1ActionPerformed(evt);
            }
        });
        getContentPane().add(jcb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 115, 64, 25));

        jLabel11.setText("enrollno");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 75, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 72, 101, -1));

        jButton2.setText("enter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 71, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel12.setText("Theory Attendance");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 434, 196, 38));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel13.setText("Practical Attendance");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 436, 196, 35));

        jLabel14.setText("Total Classes :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 105, 28));

        jLabel15.setText("Total Attendance :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 536, 94, 30));

        jLabel16.setText("% of Total Attendance :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 585, 94, 29));

        jLabel17.setText("Special Attendance :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 632, 94, 25));
        getContentPane().add(jtf12, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 536, 91, 27));

        jtf13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf13ActionPerformed(evt);
            }
        });
        getContentPane().add(jtf13, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 587, 91, 25));
        getContentPane().add(jtf14, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 632, 91, -1));

        jLabel18.setText("Total Labs :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 490, 133, 27));

        jLabel19.setText("Total Attendance :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 540, 133, 22));

        jLabel20.setText("% of Practical Attendance :");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 584, -1, 30));

        jLabel21.setText("Final Attendance :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 632, 133, 25));
        getContentPane().add(jtf15, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 495, 112, 20));
        getContentPane().add(jtf16, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 536, 112, 30));
        getContentPane().add(jtf17, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 584, 112, 30));
        getContentPane().add(jtf18, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 632, 112, 25));
        getContentPane().add(jtf11, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 492, 91, 25));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setText("UPDATE RECORDS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 670, 169, 36));
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 683, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Save Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 673, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb2ActionPerformed

    private void jtf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf6ActionPerformed

    private void jcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb1ActionPerformed

    private void jtf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf5ActionPerformed

    private void jtf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String enroll=jTextField1.getText();
        StudentBean s=new StudentBean();
        AttendanceBean1 ab=new AttendanceBean1();
        s.getRecord(enroll);
        ab.getRecord(enroll);
      //  AttendanceInsertionform1 af1=new AttendanceInsertionform1();
        //af1.setVisible(true);

         jtf1.setText(s.getsenrollno());
        jtf2.setText(s.getSfirstname());
        jtf3.setText(s.getSlastname());
        jtf4.setText(s.getSfname());
        jtf5.setText(s.getSmobile());
        jtf6.setText(s.getSemail());
        jtf7.setText(s.getSaddress());
        jcb1.setSelectedItem(s.getSbranch());
       String sem=Integer.toString(s.getSsem());
        jcb2.setSelectedItem(sem);
        System.out.println(ab.getAttotal());
         String attotal=Integer.toString(ab.getAttotal());
        jtf11.setText(attotal);
        jtf12.setText(Integer.toString(ab.getAtattended()));
        jtf13.setText(Double.toString(ab.getAtpercentage()));
        jtf15.setText(Integer.toString(ab.getAptotal()));
        jtf16.setText(Integer.toString(ab.getApattended()));
        jtf17.setText(Double.toString(ab.getAppercentage()));
        jtf14.setText(Integer.toString(ab.getAspecial()));
        jtf18.setText(Double.toString(ab.getAfinal()));

       // jButton1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtf13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

       s.setsenrollno(jtf1.getText());
        s.setSfirstname(jtf2.getText());
        s.setSlastname(jtf3.getText());
        s.setSfname(jtf4.getText());
        s.setSbranch(jcb1.getSelectedItem().toString());
        
        s.setSsem(Integer.parseInt(jcb2.getSelectedItem().toString()));
        s.setSmobile(jtf5.getText());
        s.setSemail(jtf6.getText());
        s.setSaddress(jtf7.getText());

ab.setSenrollno(jtf1.getText());
ab.setAttotal(Integer.parseInt(jtf11.getText()));
ab.setAtattended(Integer.parseInt(jtf12.getText()));
ab.setAtpercentage(Double.parseDouble(jtf13.getText()));
ab.setAptotal(Integer.parseInt(jtf15.getText()));
ab.setApattended(Integer.parseInt(jtf16.getText()));

ab.setAppercentage(Double.parseDouble(jtf17.getText()));
ab.setAspecial(Integer.parseInt(jtf14.getText()));
ab.setAfinal(Double.parseDouble(jtf18.getText()));
boolean b=ab.update();
boolean b1=s.update();
if(b&&b1){
    jLabel22.setText("Data Insertion Successfully!");
}
 else {
    jLabel22.setText("Data Insertion Failure!");
}
         jtf1.setText("");
        jtf2.setText("");
        jtf3.setText("");
        jtf4.setText("");
        jtf5.setText("");
        jtf6.setText("");
        jtf7.setText("");
        jcb1.setSelectedItem("");

        jcb2.setSelectedItem("");
        System.out.println("");

        jtf11.setText("");
        jtf12.setText("");
        jtf13.setText("");
        jtf15.setText("");
        jtf16.setText("");
        jtf17.setText("");
        jtf14.setText("");
        jtf18.setText("");


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ttotal=Double.parseDouble(jtf11.getText());
        tattended=Double.parseDouble(jtf12.getText());

        tpercentage=(tattended/ttotal)*100;
       // System.out.print(tpercentage);
        ptotal=Double.parseDouble(jtf15.getText());
        pattended=Double.parseDouble(jtf16.getText());
        ppercentage=(pattended/ptotal)*100;
        aspecial=Double.parseDouble(jtf14.getText());
        afinal=((tattended+aspecial)/ttotal)*100;

        jtf13.setText(Double.toString(tpercentage));
        jtf17.setText(Double.toString(ppercentage));
        jtf18.setText(Double.toString(afinal));
        jButton1.setEnabled(false);
        jButton3.setEnabled(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    
        public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendanceUpdationform().setVisible(true);
            }
        });
    }
AttendanceBean1 ab=new AttendanceBean1();
StudentBean s=new StudentBean();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox jcb1;
    private javax.swing.JComboBox jcb2;
    private javax.swing.JTextField jtf1;
    private javax.swing.JTextField jtf11;
    private javax.swing.JTextField jtf12;
    private javax.swing.JTextField jtf13;
    private javax.swing.JTextField jtf14;
    private javax.swing.JTextField jtf15;
    private javax.swing.JTextField jtf16;
    private javax.swing.JTextField jtf17;
    private javax.swing.JTextField jtf18;
    private javax.swing.JTextField jtf2;
    private javax.swing.JTextField jtf3;
    private javax.swing.JTextField jtf4;
    private javax.swing.JTextField jtf5;
    private javax.swing.JTextField jtf6;
    private javax.swing.JTextArea jtf7;
    // End of variables declaration//GEN-END:variables

}
