/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudentInfoList.java
 *
 * Created on 8 May, 2016, 8:16:09 AM
 */

package com.student.attendance;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YASH KUMAR
 */
public class StudentInfoList extends javax.swing.JFrame {

    /** Creates new form StudentInfoList */
    int tot = 0, cur = 0;
static int ssem=0;
   DefaultTableModel model;

    public StudentInfoList(int sem) {
        
        
        
         ssem=sem;


    /** Creates new form EmployePanel */
            s = new StudentBean();
        int num = s.getTotal(sem);
       if (num >= 1) {
            cur = 1;
            tot = num;
         //   s = s.getRecord(1);
            //show(e);
        }

       

        
        initComponents();
    



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EnrollmentNo", "FirstName", "LastName", "Father NAme", "Branch", "Semester", "Mobile", "Email", "Address", "Attendance Theory Total ", "Theory Attended", "Theory Percentage", "Attendence Practical Total", "Practical Attended", "Practical Percentage", "Special Attendance", "Final Percentage"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel1.setText("Students Record List");

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton1)
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                int i=1;
for(i=1;i<=tot;i++){
 Vector q=new Vector();
s.getRecord(i,ssem);
s.getSid();


q.addElement(s.getsenrollno());
q.addElement(s.getSfirstname());
q.addElement(s.getSlastname());
q.addElement(s.getSfname());
q.addElement(s.getSbranch());
q.addElement(s.getSsem());
q.addElement(s.getSmobile());
q.addElement(s.getSemail());
q.addElement(s.getSaddress());


Vector rows = new Vector();

              rows.addElement(q);
           DefaultTableModel model=(DefaultTableModel) jTable1.getModel();

        model.addRow(q);

// TODO add your handling code here:


        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

         DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
         AttendanceInsertionform1 af1=new AttendanceInsertionform1();
         af1.setVisible(true);
 //       af1.setText(model.getValueAt(jTable1.getSelectedRow(),0).toString());
 //jtf2.setText(model.getValueAt(jTable1.getSelectedRow(),1).toString());
  //jtf3.setText(model.getValueAt(jTable1.getSelectedRow(),2).toString());

  cur=Integer.parseInt(model.getValueAt(jTable1.getSelectedRow(),3).toString());


    }//GEN-LAST:event_jTable1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new StudentInfoList().setVisible(true);
            }
        });
    }
StudentBean s=new StudentBean();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
